---

services:
  nginx-a:
    image: nginx
    volumes:
      - ./data/nginx:/var/log/nginx/
      - ./wwwA:/usr/share/nginx/html:ro

  fluentbit:
    image: fluent/fluent-bit:1.8
    depends_on:
      - nginx-a
      - chevillette
    volumes:
      - ./data/nginx:/var/log/nginx/
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - 2020

  chevillette:
    image: busybox
    command: chevillette
    expose:
     - 8080
     - 24224
    volumes:
     - ../bin/chevillette:/usr/local/bin/chevillette:ro
     - ./chevillette.yml:/etc/chevillette.yml:ro

  nginx-b:
    image: nginx
    volumes:
     - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - chevillette

  client:
    image: curlimages/curl
    depends_on:
      - nginx-a
      - nginx-b
    command: /bin/sh
